FROM python:3.11
WORKDIR /app
COPY pyproject.toml /app
RUN apt update \
&& apt install libreoffice --no-install-recommends default-jre libreoffice-java-common python3 curl traceroute iproute2 inetutils-ping -y \
&& apt-get clean && curl -sSL https://install.python-poetry.org | python3 - \
     && export PATH="/root/.local/bin:$PATH" \
     && ln -s /root/.local/bin/poetry /usr/local/bin/poetry \
     && rm -rf /var/lib/apt/lists/* \
     && poetry install --no-root --no-interaction --no-ansi \
     && poetry cache list \
     && poetry cache clear PyPI --all --no-interaction \
     && rm -rf /root/.cache/pypoetry/artifacts/*
ENV PATH="/root/.cache/pypoetry/virtualenvs/presentation-make-9TtSrW0h-py3.11/bin:$PATH"
RUN rm -rf pyproject.toml

CMD sh -c "traceroute google.com"
