import asyncio
import logging
import os

from make_presentation import Presentation
from make_presentation.config import path_to_file

absolute_path = os.path.dirname(os.path.dirname(__file__))
save_path_for_images = os.path.join(path_to_file, "images")
logging.basicConfig(
    level=logging.INFO,
    filename=os.path.join(absolute_path, "presentation_make", "log_file.log"),
    filemode="w",
    encoding="utf-8"
)

context = """
solar system, assemblage consisting of the Sun—an average star in the Milky Way Galaxy—and those bodies orbiting around it: 8 (formerly 9) planets with more than 400 known planetary satellites (moons); many asteroids, some with their own satellites; comets and other icy bodies; and vast reaches of highly tenuous gas and dust known as the interplanetary medium. The solar system is part of the "observable universe," the region of space that humans can actually or theoretically observe with the aid of technology. Unlike the observable universe, the universe is possibly infinite.
The Sun, Moon, and brightest planets were visible to the naked eyes of ancient astronomers, and their observations and calculations of the movements of these bodies gave rise to the science of astronomy. Today the amount of information on the motions, properties, and compositions of the planets and smaller bodies has grown to immense proportions, and the range of observational instruments has extended far beyond the solar system to other galaxies and the edge of the known universe. Yet the solar system and its immediate outer boundary still represent the limit of our physical reach, and they remain the core of our theoretical understanding of the cosmos as well. Earth-launched space probes and landers have gathered data on planets, moons, asteroids, and other bodies, and this data has been added to the measurements collected with telescopes and other instruments from below and above Earth’s atmosphere and to the information extracted from meteorites and from Moon rocks returned by astronauts. All this information is scrutinized in attempts to understand in detail the origin and evolution of the solar system—a goal toward which astronomers continue to make great strides.
Composition of the solar system orbits
The orbits of the planets and other bodies of the solar system.
Located at the centre of the solar system and influencing the motion of all the other bodies through its gravitational force is the Sun, which in itself contains more than 99 percent of the mass of the system. The planets, in order of their distance outward from the Sun, are Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, and Neptune. Four planets—Jupiter through Neptune—have ring systems, and all but Mercury and Venus have one or more moons. Pluto had been officially listed among the planets since it was discovered in 1930 orbiting beyond Neptune, but in 1992 an icy object was discovered still farther from the Sun than Pluto. Many other such discoveries followed, including an object named Eris that appears to be at least as large as Pluto. It became apparent that Pluto was simply one of the larger members of this new group of objects, collectively known as the Kuiper belt. Accordingly, in August 2006 the International Astronomical Union (IAU), the organization charged by the scientific community with classifying astronomical objects, voted to revoke Pluto’s planetary status and place it under a new classification called dwarf planet. For a discussion of that action and of the definition of planet approved by the IAU, see planet.
Any natural solar system object other than the Sun, a planet, a dwarf planet, or a moon is called a small body; these include asteroids, meteoroids, and comets. Most of the more than one million asteroids, or minor planets, orbit between Mars and Jupiter in a nearly flat ring called the asteroid belt. The myriad fragments of asteroids and other small pieces of solid matter (smaller than a few tens of metres across) that populate interplanetary space are often termed meteoroids to distinguish them from the larger asteroidal bodies.
The solar system’s several billion comets are found mainly in two distinct reservoirs. The more-distant one, called the Oort cloud, is a spherical shell surrounding the solar system at a distance of approximately 50,000 astronomical units (AU)—more than 1,000 times the distance of Pluto’s orbit. The other reservoir, the Kuiper belt, is a thick disk-shaped zone whose main concentration extends 30–50 AU from the Sun, beyond the orbit of Neptune but including a portion of the orbit of Pluto. (One astronomical unit is the average distance from Earth to the Sun—about 150 million km [93 million miles].) Just as asteroids can be regarded as rocky debris left over from the formation of the inner planets, Pluto, its moon Charon, Eris, and the myriad other Kuiper belt objects can be seen as surviving representatives of the icy bodies that accreted to form the cores of Neptune and Uranus. As such, Pluto and Charon may also be considered to be very large comet nuclei. The Centaur objects, a population of comet nuclei having diameters as large as 200 km (125 miles), orbit the Sun between Jupiter and Neptune, probably having been gravitationally perturbed inward from the Kuiper belt. The interplanetary medium—an exceedingly tenuous plasma (ionized gas) laced with concentrations of dust particles—extends outward from the Sun to about 123 AU.
The solar system even contains objects from interstellar space that are just passing through. Two such interstellar objects have been observed. ‘Oumuamua had an unusual cigarlike or pancakelike shape and was possibly composed of nitrogen ice. Comet Borisov was much like the comets of the solar system but with a much higher abundance of carbon monoxide.
Orbits
solar system to scaleThe eight planets of the solar system and Pluto, in a montage of images scaled to show the approximate sizes of the bodies relative to one another. Outward from the Sun, which is represented to scale by the yellow segment at the extreme left, are the four rocky terrestrial planets (Mercury, Venus, Earth, and Mars), the four hydrogen-rich giant planets (Jupiter, Saturn, Uranus, and Neptune), and icy, comparatively tiny Pluto.

All the planets and dwarf planets, the rocky asteroids, and the icy bodies in the Kuiper belt move around the Sun in elliptical orbits in the same direction that the Sun rotates. This motion is termed prograde, or direct, motion. Looking down on the system from a vantage point above Earth’s North Pole, an observer would find that all these orbital motions are in a counterclockwise direction. In striking contrast, the comet nuclei in the Oort cloud are in orbits having random directions, corresponding to their spherical distribution around the plane of the planets.

The shape of an object’s orbit is defined in terms of its eccentricity. For a perfectly circular orbit, the eccentricity is 0; with increasing elongation of the orbit’s shape, the eccentricity increases toward a value of 1, the eccentricity of a parabola. Of the eight major planets, Venus and Neptune have the most circular orbits around the Sun, with eccentricities of 0.007 and 0.009, respectively. Mercury, the closest planet, has the highest eccentricity, with 0.21; the dwarf planet Pluto, with 0.25, is even more eccentric. Another defining attribute of an object’s orbit around the Sun is its inclination, which is the angle that it makes with the plane of Earth’s orbit—the ecliptic plane. Again, of the planets, Mercury’s has the greatest inclination, its orbit lying at 7° to the ecliptic; Pluto’s orbit, by comparison, is much more steeply inclined, at 17.1°. The orbits of the small bodies generally have both higher eccentricities and higher inclinations than those of the planets. Some comets from the Oort cloud have inclinations greater than 90°; their motion around the Sun is thus opposite that of the Sun’s rotation, or retrograde.
Planets and their moons

The eight planets can be divided into two distinct categories on the basis of their densities (mass per unit volume). The four inner, or terrestrial, planets—Mercury, Venus, Earth, and Mars—have rocky compositions and densities greater than 3 grams per cubic cm. (Water has a density of 1 gram per cubic cm.) In contrast, the four outer planets, also called the Jovian, or giant, planets—Jupiter, Saturn, Uranus, and Neptune—are large objects with densities less than 2 grams per cubic cm; they are composed primarily of hydrogen and helium (Jupiter and Saturn) or of ice, rock, hydrogen, and helium (Uranus and Neptune). The dwarf planet Pluto is unique—an icy, low-density body smaller than Earth’s Moon, more similar to comets or to the large icy moons of the outer planets than to any of the planets themselves. Its acceptance as a member of the Kuiper belt explains these anomalies.

The relatively small inner planets have solid surfaces, lack ring systems, and have few or no moons. The atmospheres of Venus, Earth, and Mars are composed of a significant percentage of oxidized compounds such as carbon dioxide. Among the inner planets, only Earth has a strong magnetic field, which shields it from the interplanetary medium. The magnetic field traps some of the electrically charged particles of the interplanetary medium inside a region around Earth known as the magnetosphere. Heavy concentrations of these high-energy particles occur in the Van Allen belts in the inner part of the magnetosphere.
Jovian planets
Jovian planetsThe Jovian—or gaseous, Jupiter-like—planets.

The four giant outer planets are much more massive than the terrestrial planets and have immense atmospheres composed mainly of hydrogen and helium. They have no solid surfaces, however, and their densities are so low that one of them, Saturn, would actually float in water. Each of the outer planets has a magnetic field, a ring system, and many known moons, with more likely to be discovered. Pluto has no known rings and only five known moons. Several other Kuiper belt objects and some asteroids also have moons of their own.

Most of the known moons move around their respective planets in the same direction that the planets orbit the Sun. They are extremely diverse, representing a wide range of environments. Jupiter is orbited by Io, a body wracked by intense volcanism, while Saturn’s largest moon, Titan—a body larger than the terrestrial planet Mercury—exhibits a primitive atmosphere denser than that of Earth. Triton moves in a retrograde orbit around Neptune—that is, opposite to the direction of the planet’s orbit around the Sun—and features plumes of material rising through its tenuous atmosphere from a surface whose temperature is only 37 kelvins (K; −393 °F, −236 °C).
Asteroids and comets
Gaspra
GaspraGaspra, an asteroid of the main belt, in a composite of two images taken by the Galileo spacecraft during its flyby on October 29, 1991. Pocked with numerous small craters, Gaspra measures about 20 km (12 miles) in its longest dimension. Its irregular shape and groovelike linear markings suggest that it was once part of a larger body that experienced one or more shattering collisions. Colours in the composite image have been enhanced by computer to highlight subtle variations in reflectivity and other surface characteristics.

The asteroids and comets are remnants of the planet-building process in the inner and outer solar system, respectively. The asteroid belt is home to rocky bodies ranging in size from the largest known asteroid, Ceres (also classified by the IAU as a dwarf planet), with a diameter of roughly 940 km (585 miles), to microscopic dust particles that are dispersed throughout the belt. Some asteroids travel in paths that cross the orbit of Earth, providing opportunities for collisions with the planet. The rare collisions of relatively large objects (those with diameters greater than about 1 km [0.6 mile]) with Earth can be devastating, as in the case of the asteroid impact that is thought to have been responsible for the massive extinction of species at the end of the Cretaceous Period 65 million years ago (see dinosaur: Extinction; Earth impact hazard). More commonly, the impacting objects are much smaller, reaching Earth’s surface as meteorites. Asteroid observations from Earth, which have been confirmed by spacecraft flybys, indicate that some asteroids are mainly metal (principally iron), others are stony, and still others are rich in organic compounds, resembling the carbonaceous chondrite meteorites. The asteroids that have been visited by spacecraft are irregularly shaped objects pockmarked with craters; some of them have retained very primitive material from the early days of the solar system.
Comet Wild 2
Comet Wild 2The icy nucleus of Comet Wild 2, in a composite image taken by the U.S. Stardust spacecraft during its close approach to the comet on January 2, 2004. The image consists of a short exposure to resolve fine details of the surface and a longer exposure to capture the faint jets of gas and dust streaming into space. Wild 2's nucleus is about 5 km (3 miles) across.

The physical characteristics of comet nuclei are fundamentally different from those of asteroids. Ices are their main constituent, predominantly frozen water, but frozen carbon dioxide, carbon monoxide, methanol, and other ices are also present. These cosmic ice balls are laced with rock dust and a rich variety of organic compounds, many of which are collected in tiny grains. Some comets may have more such “dirt” than ice.

Comets can be classified according to their orbital period, the time it takes for them to revolve around the Sun. Comets that have orbital periods greater than 200 years (and usually much greater) are called long-period comets; those that make a return appearance in less time are short-period comets. Each kind appears to have a distinct source.

The nucleus of a typical long-period comet is irregularly shaped and a few kilometres across. It can have an orbital period of millions of years, and it spends most of its life at immense distances from the Sun, as much as one-fifth of the way to the nearest star. This is the realm of the Oort cloud. The comet nuclei in this spherical shell are too distant to be visible from Earth. The presence of the cloud is presumed from the highly elliptical orbits—with eccentricities close to 1—in which the long-period comets are observed as they approach and then swing around the Sun. Their orbits can be inclined in any direction—hence the inference that the Oort cloud is spherical. In contrast, most short-period comets, particularly those with periods of 20 years or less, move in rounder, prograde orbits near the plane of the solar system. Their source is believed to be the much nearer Kuiper belt, which lies in the plane of the solar system beyond the orbit of Neptune. Comet nuclei in the Kuiper belt have been photographed from Earth with large telescopes.
Hear about the band of dust and debris left by comets, which are visible as meteors (shooting stars)
Hear about the band of dust and debris left by comets, which are visible as meteors (shooting stars)Learn about comet debris, including meteors (shooting stars).
See all videos for this article

As comet nuclei trace out the parts of their orbits closest to the Sun, they are warmed through solar heating and begin to shed gases and dust, which form the familiar fuzzy-looking comas and long, wispy tails. The gas dissipates into space, but the grains of silicates and organic compounds remain to orbit the Sun along paths very similar to that of the parent comet. When Earth’s path around the Sun intersects one of these dust-populated orbits, a meteor shower occurs. During such an event, nighttime observers may see tens to hundreds of so-called shooting stars per hour as the dust grains burn up in the upper atmosphere of Earth. Although many random meteors can be observed nightly, they occur at a much higher rate during a meteor shower. Even on an average day, Earth’s atmosphere is bombarded with more than 80 tons of dust grains, mostly asteroidal and cometary debris.
The interplanetary medium

In addition to particles of debris (see interplanetary dust particle), the space through which the planets travel contains protons, electrons, and ions of the abundant elements, all streaming outward from the Sun in the form of the solar wind. Occasional giant solar flares, short-lived eruptions on the Sun’s surface, expel matter (along with high-energy radiation) that contributes to this interplanetary medium.

In 2012 the space probe Voyager 1 crossed the boundary between the interplanetary medium and the interstellar medium—a region called the heliopause. Since passing through the heliopause, Voyager 1 has been able to measure the properties of interstellar space.
Origin of the solar system

As the amount of data on the planets, moons, comets, and asteroids has grown, so too have the problems faced by astronomers in forming theories of the origin of the solar system. In the ancient world, theories of the origin of Earth and the objects seen in the sky were certainly much less constrained by fact. Indeed, a scientific approach to the origin of the solar system became possible only after the publication of Isaac Newton’s laws of motion and gravitation in 1687. Even after this breakthrough, many years elapsed while scientists struggled with applications of Newton’s laws to explain the apparent motions of planets, moons, comets, and asteroids. In 1734 Swedish philosopher Emanuel Swedenborg proposed a model for the solar system’s origin in which a shell of material around the Sun broke into small pieces that formed the planets. This idea of the solar system forming out of an original nebula was extended by the German philosopher Immanuel Kant in 1755.
Early scientific theories
The Kant-Laplace nebular hypothesis

Kant’s central idea was that the solar system began as a cloud of dispersed particles. He assumed that the mutual gravitational attractions of the particles caused them to start moving and colliding, at which point chemical forces kept them bonded together. As some of these aggregates became larger than others, they grew still more rapidly, ultimately forming the planets. Because Kant was not highly versed in physics or mathematics, he did not recognize the intrinsic limitations of his approach. His model does not account for planets moving around the Sun in the same direction and in the same plane, as they are observed to do, nor does it explain the revolution of planetary satellites.

A significant step forward was made by Pierre-Simon Laplace of France some 40 years later. A brilliant mathematician, Laplace was particularly successful in the field of celestial mechanics. Besides publishing a monumental treatise on the subject, Laplace wrote a popular book on astronomy, with an appendix in which he made some suggestions about the origin of the solar system.

Laplace’s model begins with the Sun already formed and rotating and its atmosphere extending beyond the distance at which the farthest planet would be created. Knowing nothing about the source of energy in stars, Laplace assumed that the Sun would start to cool as it radiated away its heat. In response to this cooling, as the pressure exerted by its gases declined, the Sun would contract. According to the law of conservation of angular momentum, the decrease in size would be accompanied by an increase in the Sun’s rotational velocity. Centrifugal acceleration would push the material in the atmosphere outward, while gravitational attraction would pull it toward the central mass; when these forces just balanced, a ring of material would be left behind in the plane of the Sun’s equator. This process would have continued through the formation of several concentric rings, each of which then would have coalesced to form a planet. Similarly, a planet’s moons would have originated from rings produced by the forming planets.

Laplace’s model led naturally to the observed result of planets revolving around the Sun in the same plane and in the same direction as the Sun rotates. Because the theory of Laplace incorporated Kant’s idea of planets coalescing from dispersed material, their two approaches are often combined in a single model called the Kant-Laplace nebular hypothesis. This model for solar system formation was widely accepted for about 100 years. During this period, the apparent regularity of motions in the solar system was contradicted by the discovery of asteroids with highly eccentric orbits and moons with retrograde orbits. Another problem with the nebular hypothesis was the fact that, whereas the Sun contains 99.9 percent of the mass of the solar system, the planets (principally the four giant outer planets) carry more than 99 percent of the system’s angular momentum. For the solar system to conform to this theory, either the Sun should be rotating more rapidly or the planets should be revolving around it more slowly.
View of the Andromeda Galaxy (Messier 31, M31).
Britannica Quiz
Astronomy and Space Quiz
Twentieth-century developments

In the early decades of the 20th century, several scientists decided that the deficiencies of the nebular hypothesis made it no longer tenable. The Americans Thomas Chrowder Chamberlin and Forest Ray Moulton and later James Jeans and Harold Jeffreys of Great Britain developed variations on the idea that the planets were formed catastrophically—i.e., by a close encounter of the Sun with another star. The basis of this model was that material was drawn out from one or both stars when the two bodies passed at close range, and this material later coalesced to form planets. A discouraging aspect of the theory was the implication that the formation of solar systems in the Milky Way Galaxy must be extremely rare, because sufficiently close encounters between stars would occur very seldom.

The next significant development took place in the mid-20th century as scientists acquired a more-mature understanding of the processes by which stars themselves must form and of the behaviour of gases within and around stars. They realized that hot gaseous material stripped from a stellar atmosphere would simply dissipate in space; it would not condense to form planets. Hence, the basic idea that a solar system could form through stellar encounters was untenable. Furthermore, the growth in knowledge about the interstellar medium—the gas and dust distributed in the space separating the stars—indicated that large clouds of such matter exist and that stars form in these clouds. Planets must somehow be created in the process that forms the stars themselves. This awareness encouraged scientists to reconsider certain basic processes that resembled some of the earlier notions of Kant and Laplace.
Modern ideas

The current approach to the origin of the solar system treats it as part of the general process of star formation. As observational information has steadily increased, the field of plausible models for this process has narrowed. This information ranges from observations of star-forming regions in giant interstellar clouds to subtle clues revealed in the existing chemical composition of the objects present in the solar system. Many scientists have contributed to the modern perspective, most notably the Canadian-born American astrophysicist Alistair G.W. Cameron.
Formation of the solar nebula
Discover how the solar system, which started as a shapeless spherical blob ended up being flat
1 of 2
Discover how the solar system, which started as a shapeless spherical blob ended up being flatLearn how the solar system, which formed from a roughly spherical cloud, became flat.
See all videos for this article
solar system
2 of 2
solar systemArtist's conception of a young version of the solar system depicting the dusty disks thought to be the breeding grounds of planets.

The favoured paradigm for the origin of the solar system begins with the gravitational collapse of part of an interstellar cloud of gas and dust having an initial mass only 10–20 percent greater than the present mass of the Sun. This collapse could be initiated by random fluctuations of density within the cloud, one or more of which might result in the accumulation of enough material to start the process, or by an extrinsic disturbance such as the shock wave from a supernova. The collapsing cloud region quickly becomes roughly spherical in shape. Because it is revolving around the centre of the Galaxy, the parts more distant from the centre are moving more slowly than the nearer parts. Hence, as the cloud collapses, it starts to rotate, and, to conserve angular momentum, its speed of rotation increases as it continues to contract. With ongoing contraction, the cloud flattens, because it is easier for matter to follow the attraction of gravity perpendicular to the plane of rotation than along it, where the opposing centrifugal force is greatest. The result at this stage, as in Laplace’s model, is a disk of material formed around a central condensation.
View an animation of a brown dwarf surrounded by a swirling disk of planet-building dust
View an animation of a brown dwarf surrounded by a swirling disk of planet-building dustComputer animation showing a brown dwarf surrounded by a swirling disk of planet-building dust.
See all videos for this article

This configuration, commonly referred to as the solar nebula, resembles the shape of a typical spiral galaxy on a much reduced scale. As gas and dust collapse toward the central condensation, their potential energy is converted to kinetic energy (energy of motion), and the temperature of the material rises. Ultimately the temperature becomes great enough within the condensation for nuclear reactions to begin, thereby giving birth to the Sun.

Meanwhile, the material in the disk collides, coalesces, and gradually forms larger and larger objects, as in Kant’s theory. Because most of the grains of material have nearly identical orbits, collisions between them are relatively mild, which allows the particles to stick and remain together. Thus, larger agglomerations of particles are gradually built up.
Differentiation into inner and outer planets

At this stage the individual accreting objects in the disk show differences in their growth and composition that depend on their distances from the hot central mass. Close to the nascent Sun, temperatures are too high for water to condense from gaseous form to ice, but, at the distance of present-day Jupiter (approximately 5 AU) and beyond, water ice can form. The significance of this difference is related to the availability of water to the forming planets. Because of the relative abundances in the universe of the various elements, more molecules of water can form than of any other compound. (Water, in fact, is the second most abundant molecule in the universe, after molecular hydrogen.) Consequently, objects forming in the solar nebula at temperatures at which water can condense to ice are able to acquire much more mass in the form of solid material than objects forming closer to the Sun. Once such an accreting body achieves approximately 10 times the present mass of Earth, its gravity can attract and retain large amounts of even the lightest elements, hydrogen and helium, from the solar nebula. These are the two most abundant elements in the universe, and so planets forming in this region can become very massive indeed. Only at distances of 5 AU or more is there enough mass of material in the solar nebula to build such a planet.
geochemical cycle
More From Britannica
chemical element: Solar system

This simple picture can explain the extensive differences observed between the inner and outer planets. The inner planets formed at temperatures too high to allow the abundant volatile substances—those with comparatively low freezing temperatures—such as water, carbon dioxide, and ammonia to condense to their ices. They therefore remained small rocky bodies. In contrast, the large low-density, gas-rich outer planets formed at distances beyond what astronomers have dubbed the “snow line”—i.e., the minimum radius from the Sun at which water ice could have condensed, at about 150 K (−190 °F, −120 °C). The effect of the temperature gradient in the solar nebula can be seen today in the increasing fraction of condensed volatiles in solid bodies as their distance from the Sun increases. As the nebular gas cooled, the first solid materials to condense from a gaseous phase were grains of metal-containing silicates, the basis of rocks. This was followed, at larger distances from the Sun, by formation of the ices. In the inner solar system, Earth’s Moon, with a density of 3.3 grams per cubic cm, is a satellite composed of silicate minerals. In the outer solar system are low-density moons such as Saturn’s Tethys. With a density of about 1 gram per cubic cm, this object must consist mainly of water ice. At distances still farther out, the satellite densities rise again but only slightly, presumably because they incorporate denser solids, such as frozen carbon dioxide, that condense at even lower temperatures.

Despite its apparent logic, this scenario has received some strong challenges since the early 1990s. One has come from the discovery of other solar systems, many of which contain giant planets orbiting very close to their stars. (See below Studies of other solar systems.) Another has been the unexpected finding from the Galileo spacecraft mission that Jupiter’s atmosphere is enriched with volatile substances such as argon and molecular nitrogen (see Jupiter: Theories of the origin of the Jovian system). For these gases to have condensed and become incorporated in the icy bodies that accreted to form Jupiter’s core required temperatures of 30 K (−400 °F, −240 °C) or less. This corresponds to a distance far beyond the traditional snow line where Jupiter is thought to have formed. On the other hand, certain later models have suggested that the temperature close to the central plane of the solar nebula was much cooler (25 K [−415 °F, −248 °C]) than previously estimated.

Although a number of such problems remain to be resolved, the solar nebula model of Kant and Laplace appears basically correct. Support comes from observations at infrared and radio wavelengths, which have revealed disks of matter around young stars. These observations also suggest that planets form in a remarkably short time. The collapse of an interstellar cloud into a disk should take about one million years. The thickness of this disk is determined by the gas it contains, as the solid particles that are forming rapidly settle to the disk’s midplane, in times ranging from 100,000 years for 1-micrometre (0.00004-inch) particles to just 10 years for 1-cm (0.4-inch) particles. As the local density increases at the midplane, the opportunity becomes greater for the growth of particles by collision. As the particles grow, the resulting increase in their gravitational fields accelerates further growth. Calculations show that objects 10 km (6 miles) in size will form in just 1,000 years. Such objects are large enough to be called planetesimals, the building blocks of planets.
Later stages of planetary accretion

Continued growth by accretion leads to larger and larger objects. The energy released during accretionary impacts would be sufficient to cause vaporization and extensive melting, transforming the original primitive material that had been produced by direct condensation in the nebula. Theoretical studies of this phase of the planet-forming process suggest that several bodies the size of the Moon or Mars must have formed in addition to the planets found today. Collisions of these giant planetesimals—sometimes called planetary embryos—with the planets would have had dramatic effects and could have produced some of the anomalies seen today in the solar system—for example, the strangely high density of Mercury and the extremely slow and retrograde rotation of Venus. A collision of Earth and a planetary embryo about the size of Mars could have formed the Moon (see Moon: Origin and evolution). Somewhat smaller impacts on Mars in the late phases of accretion may have been responsible for the present thinness of the Martian atmosphere.

Studies of isotopes formed from the decay of radioactive parent elements with short half-lives, in both lunar samples and meteorites, have demonstrated that the formation of the inner planets, including Earth, and the Moon was essentially complete within 50 million years after the interstellar cloud region collapsed. The bombardment of planetary and satellite surfaces by debris left over from the main accretionary stage continued intensively for another 600 million years, but these impacts contributed only a few percent of the mass of any given object.
Formation of the outer planets and their moons

This general scheme of planet formation—the building up of larger masses by the accretion of smaller ones—occurred in the outer solar system as well. Here, however, the accretion of icy planetesimals produced objects with masses 10 times that of Earth, sufficient to cause the gravitational collapse of the surrounding gas and dust in the solar nebula. This accretion plus collapse allowed these planets to grow so large that their composition approached that of the Sun itself, with hydrogen and helium the dominant elements. Each planet started with its own “subnebula,” forming a disk around a central condensation. The so-called regular satellites of the outer planets, which today have nearly circular orbits close to the equatorial planes of their respective planets and orbital motion in the same direction as the planet’s rotation, formed from this disk. The irregular satellites—those having orbits with high eccentricity, high inclination, or both, and sometimes even retrograde motion—must represent objects formerly in orbit around the Sun that were gravitationally captured by their respective planets. Neptune’s moon Triton and Saturn’s Phoebe are prominent examples of captured moons in retrograde orbits, but every giant planet has one or more retinues of such satellites.

It is interesting that the density distribution of Jupiter’s Galilean satellites, its four largest regular moons, mirrors that of the planets in the solar system at large. The two Galilean moons closest to the planet, Io and Europa, are rocky bodies, while the more-distant Ganymede and Callisto are half ice. Models for the formation of Jupiter suggest that this giant planet was sufficiently hot during its early history that ice could not condense in the circumplanetary nebula at the present position of Io. (See Jupiter: Theories of the origin of the Jovian system.)
The small bodies

At some point after most of the matter in the solar nebula had formed discrete objects, a sudden increase in the intensity of the solar wind apparently cleared the remaining gas and dust out of the system. Astronomers have found evidence of such strong outflows around young stars. The larger debris from the nebula remained, some of which is seen today in the form of asteroids and comets. The rapid growth of Jupiter apparently prevented the formation of a planet in the gap between Jupiter and Mars; within this area remain the thousands of objects that make up the asteroid belt, whose total mass is less than one-third the mass of the Moon. The meteorites that are recovered on Earth, the great majority of which come from these asteroids, provide important clues to the conditions and processes in the early solar nebula.

The icy comet nuclei are representative of the planetesimals that formed in the outer solar system. Most are extremely small, but the Centaur object called Chiron—originally classified as a distant asteroid but now known to show characteristics of a comet—has a diameter estimated to be about 200 km (125 miles). Other bodies of this size and much larger—e.g., Pluto and Eris—have been observed in the Kuiper belt. Most of the objects occupying the Kuiper belt apparently formed in place, but calculations show that billions of icy planetesimals were gravitationally expelled by the giant planets from their vicinity as the planets formed. These objects became the population of the Oort cloud.
Formation of ring systems
Saturn
SaturnSaturn and its spectacular rings, in a natural-color composite of 126 images taken by the Cassini spacecraft on October 6, 2004. The view is directed toward Saturn's southern hemisphere, which is tipped toward the Sun. Shadows cast by the rings are visible against the bluish northern hemisphere, while the planet's shadow is projected on the rings to the left.

The formation of planetary rings remains a subject of intense research, although their existence can be easily understood in terms of their position relative to the planet that they surround. Each planet has a critical distance from its centre known as its Roche limit, named for Édouard Roche, the 19th-century French mathematician who first explained this concept. The ring systems of Jupiter, Saturn, Uranus, and Neptune lie inside the Roche limits of their respective planets. Within this distance the gravitational attraction of two small bodies for each other is smaller than the difference in the attraction of the planet for each of them. Hence, the two cannot accrete to form a larger object. Moreover, because a planet’s gravitational field acts to disperse the distribution of small particles in a surrounding disk, the random motions that would lead to accretion by collision are minimized.

The problem challenging astronomers is in understanding how and when the material making up a planet’s rings reached its present position within the Roche limit and how the rings are radially confined. These processes are likely to be very different for the different ring systems. Jupiter’s rings are clearly in a steady state between production and loss, with fresh particles continuously being supplied by the planet’s inner moons. For Saturn, scientists are divided between those who propose that the rings are remnants of the planet-forming process and those who believe that the rings must be relatively young—perhaps only a few hundred million years old. In either case, their source appears to be icy planetesimals that collided and fragmented into the small particles observed today.
Solution to the angular momentum puzzle

The angular momentum problem that defeated Kant and Laplace—why the planets have most of the solar system’s angular momentum while the Sun has most of the mass—can now be approached in a cosmic context. All stars having masses that range from slightly above the mass of the Sun to the smallest known masses rotate more slowly than an extrapolation based on the rotation rate of stars of higher mass would predict. Accordingly, these sunlike stars show the same deficit in angular momentum as the Sun itself.

The answer to how this loss could have occurred seems to lie in the solar wind. The Sun and other stars of comparable mass have outer atmospheres that are slowly but steadily expanding into space. Stars of higher mass do not exhibit such stellar winds. The loss of angular momentum associated with this loss of mass to space is sufficient to reduce the rate of the Sun’s rotation. Thus, the planets preserve the angular momentum that was in the original solar nebula, but the Sun has gradually slowed down in the 4.6 billion years since it formed.
Information from your device can be used to personalize your ad experience.

Do not sell or share my personal information.

"""


async def make_pres():
    pr = Presentation(text_generation_model="ONESTEP", template="focus")
    task2 = await pr.make_presentation(
        context="Породы котов",
        number_of_slides=None
    )
    return task2


async def main():
        print("START")                                 # noqa T201
        import time
        st = time.time()
        task1 = await make_pres()
        print(task1)                                   # noqa T201
        task2 = Presentation.save(
            data=task1,
            no_logo=True,
            save_path=path_to_file
        )
        print(task2)                                  # noqa T201

        print(f"TIME : {(time.time() - st)/60}")      # noqa T201


if __name__ == "__main__":
    asyncio.run(main())
